apiVersion: v2
name: clickstack-operators
description: >-
  Operator dependencies for ClickStack. Install this chart before
  installing clickstack/clickstack to ensure CRDs are registered.
home: https://clickhouse.com/docs/use-cases/observability/clickstack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb-kubernetes
    version: "~1.7.0"
    repository: https://mongodb.github.io/helm-charts
    alias: mongodb-operator
  - name: clickhouse-operator-helm
    version: "~0.0.2"
    repository: oci://ghcr.io/clickhouse
    alias: clickhouse-operator
