apiVersion: v1
kind: Secret
metadata:
  name: clickstack-secret
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.hyperdx.secrets }}
  {{ $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
